### PR TITLE
fix test for query issues

### PR DESCRIPTION
**Pull request by albfan**
author_id do not support contains comparator

### CODE REVIEW

**Comment by alexeyOnGitHub** [comment]
it would be great to have a test for this too

**Comment by albfan** [comment]
Will take a look. Does it need an implementation too?

**Comment by alexeyOnGitHub** [comment]
well, the implementation is there, but no tests were failing, and all tests are fine now. which means this was not checked in tests - and is not checked now.
it would be useful to have a test covering this scenario.

**Comment by albfan** [comment]
Then it should easy to do that. Let me see

**Pull request merged**
