### PR TITLE
added support for downloading files

### PR DESCRIPTION
**Pull request by AdrianD-intrafind**
The redmine API allows downloading files which is not implemented in this java client.

I suggest adding this functionality.

### CODE REVIEW

**Comment by alexeyOnGitHub** [comment]
there are no tests for this change. how did you test this? what redmine version? 

there is a config for redmine integration tests in the project, although I do not always keep the redmine VM running, so you cannot run them at any time.

it would be best to add a local redmine docker container to run the integration tests against.

**Comment by AdrianD-intrafind** [comment]
We built an application using this java api and ran it against a redmine 4 docker container.

**Comment by alexeyOnGitHub** [comment]
would it be possible for you to add the local testing setup using the docker container into this repo? 
so that people can run integration tests  on their computers without having access to my custom VM that is not always  online?
that would be the best. 

there are a few tests that would fail because they require custom setup - see the test comments. Redmine REST API does not support some operations, thus the tests rely on manually created data.

we can ignore those tests and still get useful results from a locally running test container.

**Comment by AdrianD-intrafind** [comment]
As mentioned in the other thread:
I don't feel qualified to do that and I'm not sure it's a good idea anyways.

**Review by alexeyOnGitHub — APPROVED** [review]
I did not test this change. if other people  find this useful - I am fine with merging.

**Pull request merged**
