### PR TITLE
project add status property

### PR DESCRIPTION
**Pull request by LeiXuan6**
ping , I submitted an update .

### CODE REVIEW

**Comment by LeiXuan6** [comment]
1. I have added doc and Test Cases
2. This status indicates whether the project is closed
 
Excuse me，
The status of Project, redmine written directly in the code?

**Comment by LeiXuan6** [comment]
It seems that redmine define the value of the project's status in the code. 
So I found that the status of the open project is "1" in the database and close is "5".
NOTE:  My redmine version is 3.1

**Comment by LeiXuan6** [comment]
I cannot access the redmine project (https://dev.taskadapter.com/redmine) correctlly even if I use the VPN.

please look here:
https://github.com/LeiXuan6/redmine-java-api/blob/master/img/accepnt.png

**Comment by LeiXuan6** [comment]
Could you create a account that has the privilege to manager the project at your redmine server (http://dev.taskadapter.com:8094) for me.

https://github.com/LeiXuan6/redmine-java-api/blob/master/img/error2.png

**Comment by alexeyOnGitHub** [comment]
I updated the project credentials.
the reverse proxy is broken due to Docker-Nginx issues for now.

**Comment by alexeyOnGitHub** [comment]
status numeric value can depend not only on redmine version, but on a specific db script, language or whatever else. let's not put any version-specific status codes here. the API should just return the numeric value and let user decide what to do with it. maybe their REST API has a way to get all possible project statuses ? that could be used to resolve a specific status name.
but overall let's keep it simple: the API will just return the numeric value.
some basic tests can be implemented to make sure the value is not empty, etc. nothing version-specific

**Comment by alexeyOnGitHub** [comment]
this version is now out of date. we can merge another implementation if it works ( https://github.com/taskadapter/redmine-java-api/pull/319 )

**Pull request closed without merging**
