### PR TITLE
Avoid Transfer-encoding chunked

### LINKED ISSUE #280: upload files is failing
I have done a test with curl and redmine 3.3.0: File is loaded (checked on $REDMINE_DIR/files)

response is 201:

{
  "upload": {
    "token": "32.69abd4abf577d7cfd6d370f146611fea"
  }
} 

but when it is loaded through redmine-java-api it returns a 201 but no file is uploaded on $REDMINE_DIR/files and from response: token is:

"33."

so seems last part of token is missing too

I can make any kind of test if needed. I went through transport.upload() but get lost in redmine-java-api internals

### PR DESCRIPTION
**Pull request by albfan**
redmine do not support it

resolves #280 and #278

### CODE REVIEW

**Comment by JeP42** [comment]
Would highly appreciate if someone could merge this commit since we run into same issue...

**Comment by alexeyOnGitHub** [comment]
this is more of a server configuration issue than Redmine. I mean whatever serves requests (Apache or Nginx) that are proxies to Redmine should support that.
can you please review this and make sure this works for both "Bare" Redmine (Which is only recommended for initial testing as I recall) as well as for production installations with Apache or (preferably) Nginx as web front hiding Redmine behind it?
also, need some tests verifying this change works.
then I'd be happy to merge!

**Comment by albfan** [comment]
@alexeyOnGitHub See https://github.com/taskadapter/redmine-java-api/issues/280#issuecomment-279244221 for details. Redline do not support chunked transfers

Will try to add some test to verify chunked fails (as non chunked surely will always work)

**Comment by alexeyOnGitHub** [comment]
so, the current tests all PASS with the way code is now. can you please modify tests first to make them fail with the current code? 
and then check that the proposed fix fixes the issue indeed.

**Comment by alexeyOnGitHub** [comment]
I am removing this from the next release since nobody is willing to work on this.

**Comment by albfan** [comment]
I reread all this. So the problem is in the lighthttpd implementation.

I need help to define a bare installation of redmine  (docker would be great for integration test of bare, apache or nginx) do you see another way to do it?

As this is a third party problem, do you think redmine Java API would need a config or option to setup this behaviour or it can detect redmine web front to auto configure itself?

**Comment by alexeyOnGitHub** [comment]
@albfan, I sent you Redmine dev server urls by email. 

about config options - I would have couple separate methods in the library,
one with explicit param, and another one without it, using default value.
both need to be documented (javadoc) so that it would be clear what the difference is and why use one over the other.
putting magic detection in this library would be outside of its current scope.

**Comment by albfan** [comment]
Just rebased this on top of master. After spend several time, found that openjdk comes with needed certificates to trust our redmine server.

Now I am setup. Let me rework this

**Comment by albfan** [comment]
Now uploadAttachment with lenght is documented, but how to control when derived methods can use it? I will comment on commit to review it

**Comment by albfan** [comment]
Thanks for take the time to merge this

**Pull request merged**
