### PR TITLE
Fix for #121  download attachments using API access key

### LINKED ISSUE #121: Downloading attachments not possible when connected via API access key
When calling the following constructor RedmineManager(String host, String apiAccessKey), the downloadAttachment(...) returns only the redmine html login page because the Transport doesn't contain the needed credentials.

With login and password works as expected.

### PR DESCRIPTION
**Pull request by keritaf**
Fixes #121

### CODE REVIEW

**Comment by alexeyOnGitHub** [comment]
how did you test this? I don't see any tests

**Comment by keritaf** [comment]
Almost same problem as with project custom fields in #201 - you can't actually create an attachment using Redmine REST API. Added integration test stub for the API key authentication case.

**Comment by alexeyOnGitHub** [comment]
I'm getting this error when running your test:

com.taskadapter.redmineapi.RedmineInternalError: Unsupported class class com.taskadapter.redmineapi.bean.Attachment
	at com.taskadapter.redmineapi.internal.Transport.getConfig(Transport.java:610)
	at com.taskadapter.redmineapi.internal.Transport.getObject(Transport.java:329)
	at com.taskadapter.redmineapi.internal.Transport.getObject(Transport.java:395)
	at com.taskadapter.redmineapi.AttachmentManager.getAttachmentById(AttachmentManager.java:158)
	at com.taskadapter.redmineapi.AttachmentIntegrationTest.testDownloadAttachmentContentWithAPIKey(AttachmentIntegrationTest.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)

**Comment by alexeyOnGitHub** [comment]
cannot merge until this error is fixed.

**Comment by alexeyOnGitHub** [comment]
thank you, @keritaf

**Pull request merged**
