### PR TITLE
Write custom fields for project

### LINKED ISSUE #200: Can't update project custom fields
Project custom fields are not written to JSON - as a result you can't update them

### PR DESCRIPTION
**Pull request by keritaf**
Fixes #200

### CODE REVIEW

**Comment by alexeyOnGitHub** [comment]
can you please provide some integration tests verifying that this change fixes the issue?

**Comment by keritaf** [comment]
Not sure I'll be able to do that - you can't actually _create_ custom fields using REST API (see http://www.redmine.org/issues/9664)

**Comment by keritaf** [comment]
I'm using fixed client to sync redmine 2.6 and 3.0 instances - works fine as far as I can tell

**Comment by alexeyOnGitHub** [comment]
alright, thank you for your help! someone will take a look soon

**Comment by alexeyOnGitHub** [comment]
thank you, keritaf!

**Pull request merged**
